version: "3.9"
services:
  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    ports:
      - "8000:80"

  api:
    build: .
    image: api
    command: bash -c "alembic upgrade heads && python main.py"
    ports:
      - "8001"
    container_name: api
