version: "3.9"

services:
  api:
    build: .
    image: api
    network_mode: host
    container_name: api
    env_file:
      - .env
    command: bash -c "python load_env.py && alembic upgrade heads && python main.py"
