version: "3.9"
services:
  api:
    build: .
    image: api
    command: bash -c "alembic upgrade heads && python main.py"
    ports:
      - "8001:8001"
    container_name: api
    network_mode: host
