"""Adding appointment, clients endpoints

Revision ID: 219602185dde
Revises: 742259a0512d
Create Date: 2022-12-05 00:24:03.096770

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '219602185dde'
down_revision = '742259a0512d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('appointments_timeslot_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'timeslot_id')
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'customers', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('clients', 'created_at')
    op.add_column('appointments', sa.Column('timeslot_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('appointments_timeslot_id_fkey', 'appointments', 'timeslots', ['timeslot_id'], ['id'])
    op.drop_column('appointments', 'event_id')
    # ### end Alembic commands ###
