"""Adding unique

Revision ID: 2af0ff521408
Revises: 516482fe7a2f
Create Date: 2022-08-31 22:37:19.429516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2af0ff521408'
down_revision = '516482fe7a2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agents', ['name'])
    op.create_unique_constraint(None, 'customers', ['whatsapp_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'agents', type_='unique')
    # ### end Alembic commands ###
