"""Adding created_at field at agents table

Revision ID: 742259a0512d
Revises: 2af0ff521408
Create Date: 2022-08-31 22:44:22.496439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '742259a0512d'
down_revision = '2af0ff521408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'created_at')
    # ### end Alembic commands ###
