"""Adding field calendar_id to Appointment model

Revision ID: a9de1eca9fe1
Revises: 76015d6d65ca
Create Date: 2022-12-05 16:52:55.405717

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a9de1eca9fe1'
down_revision = '76015d6d65ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'calendar_id')
    # ### end Alembic commands ###
