name: Deployment to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    steps:
      - name: testing server connection
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-191-111-168.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_EC2_KEY_PERMISSION }}
          port: 22
          script: |
            cd api
            git pull origin main
            rm .env credentials.json
            echo ${{ secrets.GCP_CREDENTIALS }} >> credentials.json
            echo ${{ secrets.API_ENV_VARIABLES }} >> .env
            sudo docker-compose up --build